### PR TITLE
Add path check

### PR DESCRIPTION
**Pull request by Fangliding**

### CODE REVIEW

**Review by tina-hello — CHANGES_REQUESTED** [review]
Can you change the default to use '' instead? That way others who already setup theirs and just merge the changes won't break their existing setup.

**Comment by tina-hello** [comment]
Also instead of handling it inside fetch(), I'd prefer if the path is taken inside handleRequest, alongside method, headers and url

**Comment by Fangliding** [comment]
> Can you change the default to use '' instead? That way others who already setup theirs and just merge the changes won't break their existing setup.

Actually, I just wanted to remind the user that the path must start with "/" , and now I have moved it to the comment

> Also instead of handling it inside fetch(), I'd prefer if the path is taken inside handleRequest, alongside method, headers and url

Done

**Comment by tina-hello** [comment]
Thank you! Merged

**Pull request merged**
